### ISSUE TITLE
Surround xml with tag

### ISSUE THREAD

**Issue by deiga** [mvz/happymapper#50]
Hi would it be possible to build a model that has a parent or surround_with notation?
Use case:
- I have class `Foo`
- It includes a list of `Bars`
- The XML representation should be surrounded by `Root`:

```
<Root>
  <Foo>
    ...
    <Bars>
      ...
    </Bars>
  </Foo>
</Root>
```

I wouldn't want to declare a class `Root` for this

**Comment by FloFra** [comment]
Open the file with nokogiri and then run ```Foo.parse(doc.xpath("Root"))```

**Comment by fidalgo** [comment]
@deiga  Isn't this provided by `wrap` https://github.com/mvz/happymapper/blob/master/spec/wrap_spec.rb

**Comment by deiga** [comment]
@fidalgo Sure, that was added a year later than this question. But this is now resolved.
