### ISSUE TITLE
Get #inner_html instead of #content

### ISSUE THREAD

**Issue by jpayne** [mvz/happymapper#62]
Is there a way to get the Nokogiri equivalent of `#inner_html` instead of `#content` from HappyMapper? Some of my XML tags contain embedded XHTML that I need to retain, but it is getting stripped out. I thought passing the `raw: true` option to elements might give the result I'm looking for, but it doesn't seem to be doing anything.

**Comment by mvz** [comment]
You should use the `XmlContent` type for such tags:

```ruby
class Foo
  include HappyMapper
  has_one 'bar', XmlContent
end
```

The 'raw' options is only used for custom parse methods.
