### ISSUE TITLE
CamelCase elements always nil

### ISSUE THREAD

**Issue by milgner** [mvz/happymapper#64]
If an element is CamelCased, its content always evaluates to `nil`:

```
pry(main)> foo = HappyMapper.parse("<foo><MessageId>f3a16e4c-b812-4934-a009-742ac51668b5</MessageId></foo>")
=> #<#<Class:0x00000002945e60>:0x000000029448d0 @message_id=nil>
pry(main)> foo.message_id
=> nil
```

Renaming the elements to lowercase yields correct content but since my input will always be camelcased, that's not an option.

**Comment by jweir** [comment]
If you need a work around until this is fixed: explicitly set the tag name:

```ruby
class Foo
  include HappyMapper

  tag 'foo'
  has_one :message_id, String, tag: 'MessageId'
end

Foo.parse "<foo><MessageId>f3a16e4c-b812-4934-a009-742ac51668b5</MessageId></foo>"
#=> <Foo:0x007fc774211798 @message_id="f3a16e4c-b812-4934-a009-742ac51668b5">

**Comment by milgner** [comment]
Thanks you for the hint. I had hoped to not need classes for every case, but I'll give it a try!
