### ISSUE TITLE
Namespace confusion

### ISSUE THREAD

**Issue by milgner** [mvz/happymapper#65]
Given a nested structure with multiple namespaces (nsa and nsb) like this:

```
<nsa:Outer>
  <nsa:Nested>
    <nsa:Inner>
      <nsb:attribute>value</nsb:attribute>
```

`Outer` is parsed correctly and `Nested` is put in, too. But while the element for `Inner` belongs to Namespace A, it's class/type is defined in Namespace B. This yields `nil` when trying to parse.

I wonder how I should specify namespaces on classes and elements here?

**Comment by milgner** [comment]
It looks like [here](https://github.com/dam5s/happymapper/blob/master/lib/happymapper.rb#L426) the namespace of the target object should be used, not of the current context.

**Comment by milgner** [comment]
Find a preliminary fix in my fork. I'll think it through some more and add some specs before creating a PR.

https://github.com/milgner/happymapper

**Comment by mvz** [comment]
I think the attribute name 'attribute' is probably a problem.
